### ISSUE TITLE
Suggestion: alternative Vril usage

### ISSUE THREAD

**Issue by frstndrd** [LTS-FFXIV/SNDScripts#1]
Where it reads `yield("/send Insert")`, maybe opt for `yield("/generalaction \"Duty Action I\"")` in order to eliminate the need for a specific keybind.

**Comment by LTS-FFXIV** [comment]
done! Thanks! gotta admit im still a bit new to all this so any other suggestions would help!

**Comment by frstndrd** [comment]
Yeah, I'm also new to it, and been using your scripts as reference, actually. 😅

While I still wasn't able to get RS running to test the Emanation EX script, I believe the same change can be made there too. Getting rid of sends usually makes my pc usable while a script is running and also makes it compatible for controller players.
