### ISSUE TITLE
Emanation (Extreme) stops after loading the instance

### ISSUE THREAD

**Issue by LuncBB** [LTS-FFXIV/SNDScripts#2]
Hi!

I was trying out the Emanation script and it appears that it hiccups around getting into the instance. When using the script it will queue for Emanation (extreme), and then rotation solver can range the enemies (but auto walky doesn't do anything), and when the boss uses the attacks that require virl the script wont use virl.

I tried auto walky separately and it worked, the queue works, but I tried the separate virl script and it didn't work. So I think it's an issue in the virl script. 

It was suggested it was a keybind issue, which is in the main page script, so I set insert but that didn't fix the issue (though I can confirm insert works now).

**Comment by LuncBB** [comment]
Was fiddling with it, it appears to be a loop issue. Too many loops in the main so it never escapes one loop to reach the next. I fixed it mostly by making a few more of the actions functions and then having them cycle.  Like one loop that goes "is X being casted?" "move player to enemy" loop again and again.

**Comment by LTS-FFXIV** [comment]
Completely reworked it lol, try it out now

**Comment by LTS-FFXIV** [comment]
by rework i mean offloaded some bits and cleaned up timings so it didnt stall
